// <auto-generated />
namespace POS.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class category_required_unique : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(category_required_unique));
        
        string IMigrationMetadata.Id
        {
            get { return "201706171025485_category_required_unique"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
