// <auto-generated />
namespace POS.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class branch_required_field : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(branch_required_field));
        
        string IMigrationMetadata.Id
        {
            get { return "201706162111288_branch_required_field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
