// <auto-generated />
namespace POS.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class general_category_required_unique_field : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(general_category_required_unique_field));
        
        string IMigrationMetadata.Id
        {
            get { return "201706170849550_general_category_required_unique_field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
