// <auto-generated />
namespace POS.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class asset_add : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(asset_add));
        
        string IMigrationMetadata.Id
        {
            get { return "201706171115350_asset_add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
